version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

# Root npm package
- package-ecosystem: npm
  directory: /
  schedule:
    interval: monthly
  assignees:
    - Sirherobrine23