name: Publish packages
on:
  release:
    types:
      - prereleased
      - released

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          registry-url: https://registry.npmjs.org/
          node-version: latest

      - name: Install dependencies
        run: npm install --no-save

      - name: Edit version
        run: npm run update_version -- ${{ github.event.release.tag_name }} --env_file=$GITHUB_ENV

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --workspaces --access public --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack package
        run: npm pack --workspaces

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.release.tag_name }}
          path: sirherobrine23-*.tgz

      - name: Upload to release
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
          tag_name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          files: sirherobrine23-*.tgz

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version
          title: Update version
          body: Update version
          branch: update-version