name: Test packages
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Package build
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install --no-save

      - name: Build packages
        run: npm run build