name: Test packages
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install --no-save

      - name: Run tests
        run: npm run --workspaces --if-present test