name: "Test"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        target:
        - ubuntu
        - windows
    runs-on: "${{ matrix.target }}-latest"
    name: "Test on ${{ matrix.target }}"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    # Install basic tools
    - uses: actions/setup-node@v3
      name: Setup node.js
      with:
        node-version: latest

    # Install dependecies
    - name: Install nodejs dependencies
      run: npm ci

    # Run test
    - name: Test
      run: npm run test
      env:
        DEBUG_DEPTH: "1000"
        DEBUG: "coreutils:*"
